language: python
python:
  - "3.6"
addons:
  chrome: beta
install:
  - wget https://chromedriver.storage.googleapis.com/2.32/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - chmod +x chromedriver
  - export $PATH=$TRAVIS_BUILD_DIR:$PATH
  - pip install selenium
script:
  - python tests.py
