sudo: required
services:
  - docker
before_install:
  - docker pull ubuntu
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu tail -f /dev/null
  - docker ps -a

install:
  - docker exec ubuntu-test bash -c "apt-get update;
    apt-get install -y software-properties-common python-software-properties;
    add-apt-repository ppa:fkrull/deadsnakes;
    apt-get update;
    apt-get install -y python3.6 python3.6-dev"

script:
  - docker exec ubuntu-test bash -c "cd /travis;
    bash test.sh;
    python3.6 test.py"
notifications:
    email: false
