sudo: required

services:
  - docker

env:
  matrix:
    - PYTHON_VER: "3.5"
    - PYTHON_VER: "3.6"

before_install:
  - docker run -d --name ubuntu-test -v $(pwd):/travis ubuntu:latest tail -f /dev/null
  - docker ps -a

install:
  - docker exec ubuntu-test bash -c "apt-get update;
    apt-get install -y libboost-regex-dev libboost-system-dev libboost-coroutine-dev libboost-context-dev libboost-filesystem-dev libboost-iostreams-dev libboost-date-time-dev libboost-thread-dev;
    apt-get install -y software-properties-common python-software-properties;
    add-apt-repository ppa:fkrull/deadsnakes;
    apt-get update;
    apt-get install -y python$PYTHON_VER python$PYTHON_VER-dev"

script:
  - docker exec ubuntu-test bash -c "cd /travis;
    python$PYTHON_VER test.py"
notifications:
    email: false
