sudo: required
services:
  - docker
language: python
python: "3.6"
before_install:
  - docker pull ubuntu
  - docker run -d --name ubuntu-test ubuntu tail -f /dev/null
  #- docker start -a ubuntu-test
  - docker ps -a
install:
  - docker exec ubuntu-test apt-get update
  - docker exec ubuntu-test apt-get install -y git build-essential python3-dev python3-pip zlib1g-dev libbz2-dev libboost-all-dev libssl-dev
  - docker exec ubuntu-test sh "cd /home"
  - docker exec ubuntu-test git clone https://github.com/romanvm/WsgiBoostServer.git
  - docker exec ubuntu-test sh "cd WsgiBoostServer"
script:
  - docker exec ubuntu-test python3 setup.py build test
notifications:
    email: false
